//Write your function calls below this line
setColor(0, 0, "blue")
setColor(0,9 , "red")
setColor(4, 5, "black")
setColor(1, 8, "red")
setColor(2, 7, "red")
setColor(3, 6, "red")
setColor(1, 1, "blue")
setColor(2, 2, "blue")
setColor(3, 3, "blue")
setColor(4, 4, "black")
setColor(3,4 , "black")
setColor(2, 4, "black")
setColor(1, 4, "black")
setColor(0, 4, "black")
setColor(3, 5, "black")
setColor(2, 5, "black")
setColor(1, 5, "black")
setColor(0, 5, "black")
setColor(0, 1, "blue")
setColor(0, 2, "blue")
setColor(1, 2, "blue")
setColor(0, 3, "blue")
setColor(1, 3, "blue")
setColor(2, 3, "blue")
setColor(0,8 , "red")
setColor(1, 8, "red")
setColor(0,7 , "red")
setColor(0,6, "red")
setColor(1,6 , "red")
setColor(2,6 , "red")
setColor(1,7 , "red")

